export const NASDAQ_100 = [
  { symbol: 'AAPL', name: 'Apple Inc.' },
  { symbol: 'MSFT', name: 'Microsoft Corp.' },
  { symbol: 'NVDA', name: 'NVIDIA Corporation' },
  { symbol: 'GOOGL', name: 'Alphabet Inc. (Class A)' },
  { symbol: 'GOOG', name: 'Alphabet Inc. (Class C)' },
  { symbol: 'AMZN', name: 'Amazon.com Inc.' },
  { symbol: 'META', name: 'Meta Platforms Inc.' },
  { symbol: 'AVGO', name: 'Broadcom Inc.' },
  { symbol: 'TSLA', name: 'Tesla Inc.' },
  { symbol: 'COST', name: 'Costco Wholesale Corp.' },
  { symbol: 'ASML', name: 'ASML Holding N.V.' },
  { symbol: 'NFLX', name: 'Netflix Inc.' },
  { symbol: 'AMD', name: 'Advanced Micro Devices Inc.' },
  { symbol: 'PEP', name: 'PepsiCo Inc.' },
  { symbol: 'LIN', name: 'Linde plc' },
  { symbol: 'CSCO', name: 'Cisco Systems Inc.' },
  { symbol: 'TMUS', name: 'T-Mobile US Inc.' },
  { symbol: 'ADBE', name: 'Adobe Inc.' },
  { symbol: 'INTU', name: 'Intuit Inc.' },
  { symbol: 'QCOM', name: 'QUALCOMM Inc.' },
  { symbol: 'TXN', name: 'Texas Instruments Inc.' },
  { symbol: 'AMGN', name: 'Amgen Inc.' },
  { symbol: 'ISRG', name: 'Intuitive Surgical Inc.' },
  { symbol: 'AMAT', name: 'Applied Materials Inc.' },
  { symbol: 'CMCSA', name: 'Comcast Corp.' },
  { symbol: 'HON', name: 'Honeywell International Inc.' },
  { symbol: 'BKNG', name: 'Booking Holdings Inc.' },
  { symbol: 'VRTX', name: 'Vertex Pharmaceuticals Inc.' },
  { symbol: 'SBUX', name: 'Starbucks Corp.' },
  { symbol: 'PANW', name: 'Palo Alto Networks Inc.' },
  { symbol: 'ADP', name: 'Automatic Data Processing Inc.' },
  { symbol: 'GILD', name: 'Gilead Sciences Inc.' },
  { symbol: 'REGN', name: 'Regeneron Pharmaceuticals Inc.' },
  { symbol: 'MDLZ', name: 'Mondelez International Inc.' },
  { symbol: 'PDD', name: 'PDD Holdings Inc.' },
  { symbol: 'INTC', name: 'Intel Corp.' },
  { symbol: 'LRCX', name: 'Lam Research Corp.' },
  { symbol: 'MELI', name: 'MercadoLibre Inc.' },
  { symbol: 'SNPS', name: 'Synopsys Inc.' },
  { symbol: 'MU', name: 'Micron Technology Inc.' },
  { symbol: 'CDNS', name: 'Cadence Design Systems Inc.' },
  { symbol: 'CRWD', name: 'CrowdStrike Holdings Inc.' },
  { symbol: 'CSX', name: 'CSX Corp.' },
  { symbol: 'PYPL', name: 'PayPal Holdings Inc.' },
  { symbol: 'KLAC', name: 'KLA Corp.' },
  { symbol: 'MAR', name: 'Marriott International Inc.' },
  { symbol: 'CTAS', name: 'Cintas Corp.' },
  { symbol: 'ORLY', name: 'O\'Reilly Automotive Inc.' },
  { symbol: 'MNST', name: 'Monster Beverage Corp.' },
  { symbol: 'ABNB', name: 'Airbnb Inc.' },
  { symbol: 'FTNT', name: 'Fortinet Inc.' },
  { symbol: 'NXPI', name: 'NXP Semiconductors N.V.' },
  { symbol: 'MRVL', name: 'Marvell Technology Inc.' },
  { symbol: 'LULU', name: 'Lululemon Athletica Inc.' },
  { symbol: 'KDP', name: 'Keurig Dr Pepper Inc.' },
  { symbol: 'WDAY', name: 'Workday Inc.' },
  { symbol: 'PCAR', name: 'PACCAR Inc.' },
  { symbol: 'DXCM', name: 'DexCom Inc.' },
  { symbol: 'MCHP', name: 'Microchip Technology Inc.' },
  { symbol: 'ROST', name: 'Ross Stores Inc.' },
  { symbol: 'AEP', name: 'American Electric Power Co. Inc.' },
  { symbol: 'KHC', name: 'The Kraft Heinz Co.' },
  { symbol: 'EXC', name: 'Exelon Corp.' },
  { symbol: 'IDXX', name: 'IDEXX Laboratories Inc.' },
  { symbol: 'PAYX', name: 'Paychex Inc.' },
  { symbol: 'CPRT', name: 'Copart Inc.' },
  { symbol: 'ODFL', name: 'Old Dominion Freight Line Inc.' },
  { symbol: 'EA', name: 'Electronic Arts Inc.' },
  { symbol: 'CHTR', name: 'Charter Communications Inc.' },
  { symbol: 'BIIB', name: 'Biogen Inc.' },
  { symbol: 'CTSH', name: 'Cognizant Technology Solutions Corp.' },
  { symbol: 'VRSK', name: 'Verisk Analytics Inc.' },
  { symbol: 'WBD', name: 'Warner Bros. Discovery Inc.' },
  { symbol: 'FAST', name: 'Fastenal Co.' },
  { symbol: 'TEAM', name: 'Atlassian Corporation' },
  { symbol: 'CSGP', name: 'CoStar Group Inc.' },
  { symbol: 'GEHC', name: 'GE HealthCare Technologies Inc.' },
  { symbol: 'ON', name: 'ON Semiconductor Corp.' },
  { symbol: 'DDOG', name: 'Datadog Inc.' },
  { symbol: 'CEG', name: 'Constellation Energy Corp.' },
  { symbol: 'BKR', name: 'Baker Hughes Co.' },
  { symbol: 'FANG', name: 'Diamondback Energy Inc.' },
  { symbol: 'ZS', name: 'Zscaler Inc.' },
  { symbol: 'MDB', name: 'MongoDB Inc.' },
  { symbol: 'TTD', name: 'The Trade Desk Inc.' },
  { symbol: 'CDW', name: 'CDW Corp.' },
  { symbol: 'ANSS', name: 'ANSYS Inc.' },
  { symbol: 'DLTR', name: 'Dollar Tree Inc.' },
  { symbol: 'ILMN', name: 'Illumina Inc.' },
  { symbol: 'WBA', name: 'Walgreens Boots Alliance Inc.' },
  { symbol: 'SIRI', name: 'Sirius XM Holdings Inc.' },
  { symbol: 'GF', name: 'GlobalFoundries Inc.' },
  { symbol: 'EBAY', name: 'eBay Inc.' },
  { symbol: 'ENPH', name: 'Enphase Energy Inc.' },
  { symbol: 'ZM', name: 'Zoom Video Communications Inc.' },
  { symbol: 'VRSN', name: 'VeriSign Inc.' },
  { symbol: 'ALGN', name: 'Align Technology Inc.' }
];
